# Homework for Week 6

The goal for this homework is to see the relevant journalistic uses for what we learned in class.

1. Ingest different types of spreadsheets into Pandas,
2. Gather general info about our dataframes
3. Target specific values

## Pandas - Importing data

Please download the following data and move it to an appropriate folder on your computer:

- <a href="https://github.com/sandeepmj/datasets/blob/main/importing-excerpts/ems20_1st_6months_excerpt.csv">EMS excerpt</a>,

- <a href="https://github.com/sandeepmj/datasets/blob/main/importing-excerpts/multi-data.xlsx">Customs, Border Patrol</a>

**Give yourself time to download it. Some of the files are large!**

In [3]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

- ```ems20_1st_6months_excerpt.csv``` into a dataframe named ```ems2020_excerpt_df```

In [32]:
## import data and store in dataframe
ems2020_excerpt_df = pd.read_csv('data/ems20_1st_6months_excerpt.csv')

In [34]:
## call the first 10 rows
ems2020_excerpt_df.head(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv
7,201471743,2020-05-26 12:45:46,INJURY,5,INJURY,5,05/26/2020 12:46:04 PM,Y,18,05/26/2020 12:46:15 PM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk171.csv
8,201180116,2020-04-27 00:57:48,EDP,7,EDPC,7,04/27/2020 12:58:07 AM,Y,19,04/27/2020 12:58:15 AM,...,50.0,11.0,208.0,10.0,16.0,N,N,N,N,chunk170.csv
9,200572739,2020-02-26 15:15:25,CARDBR,2,CARDBR,2,02/26/2020 03:16:35 PM,Y,70,02/26/2020 03:16:49 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk167.csv

In [36]:
## call the last 5 rows
ems2020_excerpt_df.tail()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [38]:
## call a 20 random rows
ems2020_excerpt_df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
4605,201771329,2020-06-25 10:29:30,SICK,6,SICK,6,06/25/2020 10:29:48 AM,Y,18,06/25/2020 10:29:58 AM,...,61.0,48.0,315.0,22.0,9.0,N,N,N,N,chunk172.csv
6419,201001543,2020-04-09 09:39:47,SICK,6,SICK,6,04/09/2020 09:40:04 AM,Y,17,04/09/2020 09:40:13 AM,...,10.0,3.0,104.0,2.0,10.0,N,N,N,N,chunk169.csv
8271,200491769,2020-02-18 11:55:50,TRAUMA,2,TRAUMA,2,02/18/2020 11:56:17 AM,Y,27,02/18/2020 11:56:40 AM,...,61.0,48.0,315.0,22.0,9.0,N,N,N,N,chunk167.csv
6260,200010194,2020-01-01 00:37:11,INJURY,5,INJURY,5,01/01/2020 12:37:32 AM,Y,21,01/01/2020 12:38:12 AM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk165.csv
12522,200742692,2020-03-14 15:10:10,INJURY,5,INJMAJ,3,03/14/2020 03:11:06 PM,Y,56,03/14/2020 03:11:22 PM,...,40.0,17.0,201.0,7.0,15.0,N,N,N,N,chunk168.csv
4751,200301512,2020-01-30 10:29:56,EDP,7,EDP,7,01/30/2020 10:30:15 AM,Y,19,01/30/2020 10:31:03 AM,...,10.0,3.0,104.0,2.0,10.0,N,N,N,N,chunk166.csv
2753,200982483,2020-04-07 11:40:46,SICK,6,SICK,6,04/07/2020 11:41:29 AM,Y,43,04/07/2020 11:41:47 AM,...,60.0,48.0,313.0,21.0,8.0,N,N,N,N,chunk169.csv
6307,200573123,2020-02-26 16:45:52,EDP,7,SICK,6,02/26/2020 04:56:06 PM,Y,614,02/26/2020 04:56:28 PM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk167.csv
8463,200203131,2020-01-20 18:16:59,UNKNOW,4,UNKNOW,4,01/20/2020 06:19:06 PM,Y,127,01/20/2020 06:19:23 PM,...,61.0,48.0,315.0,22.0,9.0,N,N,N,N,chunk165.csv
10301,201092727,2020-04-18 17:08:46,UNC,2,UNC,2,04/18/2020 05:09:01 PM,Y,15,04/18/2020 05:09:27 PM,...,75.0,37.0,305.0,19.0,8.0,N,N,N,N,chunk170.csv
12938,200740415,2020-03-14 01:59:59,INJMIN,7,INJMIN,7,03/14/2020 02:00:09 AM,Y,10,03/14/2020 02:00:51 AM,...,90.0,34.0,301.0,14.0,7.0,N,N,N,N,chunk168.csv
5753,200662655,2020-03-06 14:37:16,EDP,7,EDP,7,03/06/2020 02:43:58 PM,Y,402,03/06/2020 02:44:13 PM,...,73.0,42.0,316.0,23.0,9.0,Y,N,N,N,chunk167.csv
9281,200320578,2020-02-01 03:23:46,SICPED,4,SICPED,4,02/01/2020 03:24:24 AM,Y,38,02/01/2020 03:24:36 AM,...,44.0,14.0,204.0,9.0,15.0,N,N,N,N,chunk166.csv
3461,200060962,2020-01-06 08:00:01,DRUG,4,DIFFBR,2,01/06/2020 08:00:16 AM,Y,15,01/06/2020 08:00:31 AM,...,109.0,19.0,407.0,25.0,14.0,N,N,N,N,chunk165.csv
3184,200821921,2020-03-22 11:32:06,CARD,3,CARD,3,03/22/2020 11:32:47 AM,Y,41,03/22/2020 11:33:03 AM,...,113.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv
7142,201763214,2020-06-24 19:10:44,INJMAJ,3,INJMAJ,3,06/24/2020 07:11:21 PM,Y,37,06/24/2020 07:11:45 PM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk172.csv
7078,200131693,2020-01-13 11:01:54,RESPIR,4,RESPIR,4,01/13/2020 11:10:23 AM,Y,509,01/13/2020 11:10:44 AM,...,45.0,12.0,210.0,11.0,16.0,N,N,N,N,chunk165.csv
9657,200930666,2020-04-02 03:38:04,RESPIR,4,RESPIR,4,04/02/2020 03:38:17 AM,Y,13,04/02/2020 03:38:43 AM,...,62.0,47.0,311.0,21.0,10.0,N,N,N,N,chunk169.csv
10105,201372386,2020-05-16 16:04:02,STAB,3,STAB,3,05/16/2020 04:04:25 PM,Y,23,05/16/2020 04:04:52 PM,...,47.0,12.0,212.0,11.0,16.0,N,N,N,N,chunk170.csv
4991,200080706,2020-01-08 06:54:33,SICMIN,7,SICMIN,7,01/08/2020 06:55:01 AM,Y,28,01/08/2020 06:55:35 AM,...,25.0,8.0,111.0,4.0,13.0,N,N,N,N,chunk165.csv

In [40]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there
ems2020_excerpt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13117 entries, 0 to 13116
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CAD_INCIDENT_ID                 13117 non-null  int64
 1   INCIDENT_DATETIME               13117 non-null  object
 2   INITIAL_CALL_TYPE               13117 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     13117 non-null  int64
 4   FINAL_CALL_TYPE                 13117 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       13117 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       13010 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  13117 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    13117 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       12988 non-null  object
 10  FIRST_ON_SCENE_DATETIME         12533 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  13117 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    12533 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   12533 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          7870 non-null   object
 15  FIRST_HOSP_ARRIVAL_DATETIME     7791 non-null   object
 16  INCIDENT_CLOSE_DATETIME         13110 non-null  object
 17  HELD_INDICATOR                  13117 non-null  object
 18  INCIDENT_DISPOSITION_CODE       12985 non-null  float64
 19  BOROUGH                         13117 non-null  object
 20  INCIDENT_DISPATCH_AREA          13117 non-null  object
 21  ZIPCODE                         12987 non-null  float64
 22  POLICEPRECINCT                  12988 non-null  float64
 23  CITYCOUNCILDISTRICT             12988 non-null  float64
 24  COMMUNITYDISTRICT               12988 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         12978 non-null  float64
 26  CONGRESSIONALDISTRICT           12988 non-null  float64
 27  REOPEN_INDICATOR                13117 non-null  object
 28  SPECIAL_EVENT_INDICATOR         13117 non-null  object
 29  STANDBY_INDICATOR               13117 non-null  object
 30  TRANSFER_INDICATOR              13117 non-null  object
 31  source                          13117 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 3.2+ MB

In [42]:
## call the top 7 rows
ems2020_excerpt_df.head(7)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv

In [44]:
## call a sample of 10
ems2020_excerpt_df.sample(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
1753,200483012,2020-02-17 17:39:15,HYPTN,7,HYPTN,7,02/17/2020 05:39:28 PM,Y,13,02/17/2020 05:39:53 PM,...,83.0,37.0,304.0,32.0,8.0,N,N,N,N,chunk167.csv
6054,200891231,2020-03-29 06:33:23,SICMIN,7,SICMIN,7,03/29/2020 08:25:57 AM,Y,6754,03/29/2020 08:26:40 AM,...,67.0,45.0,317.0,17.0,9.0,N,N,N,N,chunk169.csv
7970,201670880,2020-06-15 08:29:27,DRUG,4,DRUG,4,06/15/2020 08:29:33 AM,Y,6,06/15/2020 08:29:43 AM,...,52.0,14.0,207.0,10.0,13.0,N,N,N,N,chunk171.csv
9616,200272892,2020-01-27 15:16:41,SICK,6,SICK,6,01/27/2020 03:32:18 PM,Y,937,01/27/2020 03:32:38 PM,...,17.0,4.0,106.0,2.0,12.0,N,N,N,N,chunk166.csv
7753,200023106,2020-01-02 16:06:51,CVAC,2,CARD,3,01/02/2020 04:07:26 PM,Y,35,01/02/2020 04:08:03 PM,...,13.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk165.csv
1242,200140009,2020-01-14 00:03:04,CARD,3,CARD,3,01/14/2020 12:03:30 AM,Y,26,01/14/2020 12:03:46 AM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk165.csv
2580,200741842,2020-03-14 11:36:36,CVAC,2,CVAC,2,03/14/2020 11:37:02 AM,Y,26,03/14/2020 11:37:23 AM,...,46.0,14.0,205.0,9.0,15.0,N,N,N,N,chunk168.csv
1972,200083471,2020-01-08 17:54:11,DRUG,4,DRUG,4,01/08/2020 06:16:22 PM,Y,1331,01/08/2020 06:16:43 PM,...,52.0,11.0,207.0,10.0,13.0,N,N,N,N,chunk165.csv
8545,200133221,2020-01-13 16:12:39,UNKNOW,4,UNKNOW,4,01/13/2020 04:14:15 PM,Y,96,01/13/2020 04:14:34 PM,...,103.0,24.0,412.0,28.0,5.0,N,N,N,N,chunk165.csv
11805,200270674,2020-01-27 06:00:05,SICK,6,SICK,6,01/27/2020 06:00:21 AM,Y,16,01/27/2020 06:00:36 AM,...,121.0,49.0,501.0,31.0,11.0,N,N,N,N,chunk166.csv

In [46]:
## call the bottom 6
ems2020_excerpt_df.tail(6)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13111,200870168,2020-03-27 00:42:59,INJURY,5,INJURY,5,03/27/2020 12:43:13 AM,Y,14,03/27/2020 12:43:28 AM,...,109.0,19.0,407.0,25.0,3.0,N,N,N,N,chunk168.csv
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [48]:
## Programmatically capture the 2245th FINAL_CALL_TYPE value and store in a variable.
val = ems2020_excerpt_df['FINAL_CALL_TYPE'].iloc[2244]
val

'STAB'

## Targeting an Excel sheet

Use the Customs and Border Protection data in this ```multi-data.xlsx``` workbook to answer the following questions.

Create a dataframe called ```cbp_df```.

In [71]:
## import data here
cbp_df = pd.read_excel('data/multi-data.xlsx', sheet_name=2, skiprows=6)
cbp_df

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
...,...,...,...,...,...,...,...,...,...
95716,2018-06-02 13:00:00,2018-06-04 09:05:00,44.066667,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
95717,2018-06-02 13:00:00,2018-06-04 09:05:00,44.066667,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
95718,2018-06-02 13:05:00,2018-06-05 23:35:00,82.483333,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95719,2018-06-02 13:05:00,2018-06-04 00:54:00,35.800000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
95720,2018-06-02 13:20:00,2018-06-06 07:27:00,90.100000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [73]:
## call the top 15 rows
cbp_df.head(15)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
5,2017-01-20 00:30:00,2017-01-21 15:30:00,38.983333,Under 1 year,Male,HONDURAS,SBO,(b)(7)(E ),NaN
6,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
7,2017-01-20 00:35:00,2017-01-20 15:14:00,14.633333,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
8,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
9,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
10,2017-01-20 00:45:00,2017-01-20 13:15:00,12.500000,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
11,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
12,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
13,2017-01-20 01:20:00,2017-01-24 17:30:00,112.166667,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
14,2017-01-20 01:20:00,2017-01-20 13:40:00,12.333333,9-11 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN

In [75]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there
cbp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95721 entries, 0 to 95720
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date_in           95721 non-null  datetime64[ns]
 1   date_out          95223 non-null  datetime64[ns]
 2   hours_in_custody  95506 non-null  float64
 3   age_group         95716 non-null  object
 4   gender            95721 non-null  object
 5   citizenship       95721 non-null  object
 6   border            95721 non-null  object
 7   sector            95721 non-null  object
 8   field_office      0 non-null      float64
dtypes: datetime64[ns](2), float64(2), object(5)
memory usage: 6.6+ MB

In [77]:
## call the bottom 3
cbp_df.tail(3)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
95718,2018-06-02 13:05:00,2018-06-05 23:35:00,82.483333,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95719,2018-06-02 13:05:00,2018-06-04 00:54:00,35.800000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
95720,2018-06-02 13:20:00,2018-06-06 07:27:00,90.100000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [79]:
## call a sample of 20
cbp_df.sample(20)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
75033,2018-04-04 19:05:00,2018-04-06 12:32:00,41.433333,1-2 years,Female,HONDURAS,SBO,(b)(7)(E ),NaN
74071,2018-03-31 13:00:00,2018-04-04 06:15:00,89.233333,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
75904,2018-04-08 13:50:00,2018-04-11 11:11:00,69.333333,12-14 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
15415,2017-06-26 00:30:00,2017-07-11 14:08:00,34.266667,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
74400,2018-04-02 07:00:00,2018-04-03 17:04:00,34.050000,15-18 years,Female,MEXICO,SBO,(b)(7)(E ),NaN
95054,2018-05-31 21:25:00,2018-06-03 06:48:00,57.366667,15-18 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
12547,2017-05-28 17:30:00,2017-05-29 18:24:00,24.883333,6-8 years,Female,HONDURAS,SBO,(b)(7)(E ),NaN
79877,2018-04-19 23:55:00,2018-04-20 12:03:00,12.116667,15-18 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
49829,2017-12-18 18:00:00,2017-12-23 14:19:00,116.300000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
91033,2018-05-21 22:30:00,2018-05-22 08:29:00,9.966667,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
6881,2017-02-24 18:05:00,2017-02-26 15:05:00,44.983333,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
45796,2017-12-05 15:45:00,2017-12-06 11:02:00,19.266667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
83730,2018-05-01 08:06:00,2018-05-01 14:05:00,5.983333,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
94670,2018-05-30 19:30:00,2018-06-03 14:34:00,91.050000,1-2 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
61701,2018-02-12 17:00:00,2018-02-13 12:06:00,19.083333,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
66092,2018-03-03 22:15:00,2018-03-05 08:36:00,34.333333,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
94985,2018-05-31 18:30:00,2018-06-03 12:48:00,66.283333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
57943,2018-01-25 19:43:00,2018-01-26 13:35:00,17.850000,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
25878,2017-08-31 23:00:00,2017-09-01 10:42:00,11.683333,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
69832,2018-03-17 21:45:00,2018-03-19 12:44:00,38.966667,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [81]:
## Programmatically capture the 8th hours_in_custody value and store in a variable.
val2 = cbp_df['hours_in_custody'].iloc[7]
val2

14.6333333333333